### ISSUE TITLE
missing filter icon

### ISSUE THREAD

**Issue by vorou** [appbaseio/dejaVu#14] opened 2016-03-26 09:00 UTC
I can't see the filter icons, what could be wrong?

![](http://i.imgur.com/iNyJztP.png)

elastic v1.5.1

**Comment by siddharthlatest** [comment] 2016-03-27 06:44
@vorou That's strange, filters are set based on the _mapping API of ES, and I don't see a difference between Elastic v1.5.1 and v2.x.

If you are using dejaVu from the browser, I would be curious to see any errors shown by the browser's console log.

**Comment by vorou** [comment] 2016-03-27 09:14
Well, there are tons of logs.

These ones are from Logging tab: https://gist.github.com/vorou/78a170fcc5b25783e82f
And these are from JS tab: https://gist.github.com/vorou/50b5b0aebdff7254e602

I'm using Firefox. It acts the same in Chrome.

**Comment by jdc0589** [comment] 2016-03-27 14:54
@vorou @siddharthalatest

i experienced the same issue. I almost filed an issued,  but when i went back to double check the issue,  the filters had magically appeared.

**Comment by siddharthlatest** [comment] 2016-04-30 20:13
@vorou I haven't been able to reproduce the issue, even with ES v1.5.1. It seems less likely that this is a version issue. Since the logs point to a mapping exception, is it possible for you to share a representative data set (could be 10 rows) as JSON?

**Comment by siddharthlatest** [comment] 2016-05-31 20:15
@vorou We found a bug in the code that could have caused filters to disappear in certain scenarios. Do you see this issue with the latest release ``v0.6.0`` or with the master branch (if you are using it as ES plugin)?

**Comment by vorou** [comment] 2016-06-04 10:35
I can see the filter icons now.

I'm not sure if it's related to this issue or not, but I still can't see the filter on certain columns. Some of them are nested objects (which is OK), and some of them are bools (which isn't OK, I guess).

**Comment by siddharthlatest** [comment] 2016-06-04 10:38
@vorou That's great. Filtering isn't supported on nested and bool data types and many other complex data datatypes. Adding it for bool should be easy, opening an issue for that.

I am closing this issue, as it seems it has been resolved.

**Closed by siddharthlatest** 2016-06-04 10:38 UTC
