### ISSUE TITLE
Bug demo and local

### ISSUE THREAD

**Issue by winou75** [appbaseio/dejaVu#309] opened 2019-05-20 14:49 UTC
Hey guys, the demo app don't seem to be functionnal ... 

https://dejavu.appbase.io/?appname=gitxplore-live&url=https://2FPZ2UJQW:1c50c6df-4652-4d74-906b-7bc0a6a731b6@scalr.api.appbase.io

![Capture d’écran 2019-05-20 à 16 45 31](https://user-images.githubusercontent.com/15017949/58030381-bbb5cd00-7b1e-11e9-971d-f920e3e72281.png)

Console error 

```vendors~main.3dd454ed.js:89 

TypeError: n is not a function
    at vendors~main.3dd454ed.js:67
    at Array.map (<anonymous>)
    at t.render (vendors~main.3dd454ed.js:67)
    at si (vendors~main.3dd454ed.js:89)
    at ai (vendors~main.3dd454ed.js:89)
    at di (vendors~main.3dd454ed.js:89)
    at qi (vendors~main.3dd454ed.js:89)
    at Gi (vendors~main.3dd454ed.js:89)
    at Fa (vendors~main.3dd454ed.js:89)
    at Ma (vendors~main.3dd454ed.js:89)
vi @ vendors~main.3dd454ed.js:89```

 ```An error has occured. You're using Reactivesearch Version: 3.0.0-rc.10. If you think this is a problem with Reactivesearch, please try updating to the latest version. If you're already at the latest version, please open an issue at https://github.com/appbaseio/reactivesearch/issues
r.componentDidCatch @ vendors~main.3dd454ed.js:67```

**Comment by bietkul** [comment] 2019-05-20 14:52
It seems like a cache issue, just try incognito or hard reload the browser.

**Comment by winou75** [comment] 2019-05-20 20:24
Thanks for your help.
However, it still doesn't work incognito, or hard reloading the browser

**Comment by siddharthlatest** [comment] 2019-05-20 20:27
Thanks for reporting this @winou75, I am able to replicate it. The issue is specific to the `Search Preview` view.

**Comment by siddharthlatest** [comment] 2019-05-23 11:39
This has been fixed in the latest deployment.

**Closed as completed by siddharthlatest** 2019-05-23 11:39 UTC
