### ISSUE TITLE
could not run the plugin

### ISSUE THREAD

**Issue by 0604hx** [appbaseio/dejaVu#19] opened 2016-05-24 03:20 UTC
I had installed dejaVu successful. And config as below:
`http.port: 9200

http.cors.allow-origin: "http://127.0.0.1:9200"

http.cors.enabled: true

http.cors.allow-headers : "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"

http.cors.allow-credentials: true`

but when I open http://localhost:9200/_plugin/dejaVu/, I got error:
`feed.js:19 Uncaught TypeError: Cannot read property 'split' of null(anonymous function) @ feed.js:19

main.min.js:12 Download the React DevTools for a better development experience: https://fb.me/react-devtools

main.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined`

I am using ES 2.3.2

**Comment by ronnyek** [comment] 2016-05-25 17:27
This is because of the initial data that needs to be in initial storage before stuff starts blowing up. I managed to fudge it with chrome, but certainly not for the faint of heart. Would be good to fix

**Comment by darklow** [comment] 2016-05-25 20:11
Got same problem, same error.

**Comment by siddharthlatest** [comment] 2016-05-25 20:32
@ronnyek @darklow can you tell how to reproduce this?

**Comment by darklow** [comment] 2016-05-25 20:40
I just installed plugin and tried to run it first time.
Maybe try deleting all of your existing local storage or cookies related to this plugin.
The first error appears in:
```
feed.js:19 Uncaught TypeError: Cannot read property 'split' of null
```
Which are lines:
```
var urlsplit = URL.split(':');
```
So URL is null for me.
And if I investigate further:
```js
var config = {
	url: window.localStorage.getItem('esurl'),
	appname: window.localStorage.getItem('appname')
};
var URL = config.url;
```
Since i run plugin for first time, where should `esurl` in localStorage come from?

**Comment by enefem** [comment] 2016-05-26 07:33
same here. is there any known workaround?

**Comment by farhan687** [comment] 2016-05-26 08:32
@darklow, thanks for the information.
We will fix this very soon.

**Comment by siddharthlatest** [comment] 2016-05-28 17:15
@enefem @darklow @ronnyek: this should be fixed now. Can you confirm?

**Comment by siddharthlatest** [comment] 2016-05-31 20:12
Marking this as resolved.

**Closed by siddharthlatest** 2016-05-31 20:12 UTC
