### ISSUE TITLE
Unable to Connect to SSL/TLS Enabled Elasticsearch

### ISSUE THREAD

**Issue by SLiNv** [appbaseio/dejaVu#293] opened 2019-04-14 04:20 UTC
I'm using Open Distro for Elasticsearch by Amazon, the elasticsearch instance has HTTPS enabled with self-signed certificates, which is not secure. Is there a way to bypass SSL verification like I can do in Postman.

The exception I got from the console is as following

```
odfe-node1    | [2019-04-14T04:11:26,870][ERROR][c.a.o.s.s.h.n.OpenDistroSecuritySSLNettyHttpServerTransport] [WVoWDZu] SSL Problem Received fatal alert: certificate_unknown
odfe-node1    | javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
odfe-node1    |         at sun.security.ssl.Alert.createSSLException(Alert.java:128) ~[?:?]
odfe-node1    |         at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
odfe-node1    |         at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
odfe-node1    |         at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
odfe-node1    |         at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
odfe-node1    |         at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
odfe-node1    |         at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:672) ~[?:?]
odfe-node1    |         at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:627) ~[?:?]
odfe-node1    |         at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443) ~[?:?]
odfe-node1    |         at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422) ~[?:?]
odfe-node1    |         at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634) ~[?:?]
odfe-node1    |         at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1301) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
odfe-node1    |         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by siddharthlatest** [comment] 2019-04-15 13:27
@SLiNv These are ES logs. Do you see any console logs / errors from Dejavu? Hard to infer what may be the cause from the issue so far.

**Comment by SLiNv** [comment] 2019-04-17 03:30
@siddharthlatest I see, I didn't look closer... I will try to reproduce it when I get a chance and see what the dejavu output is

**Comment by lakhansamani** [comment] 2019-05-27 05:26
This issue is related to Elasticsearch Authorization and SSL certification. So closing for now.

**Closed as completed by lakhansamani** 2019-05-27 05:26 UTC
